### ISSUE TITLE
Experiment with imports

### ISSUE THREAD

**Issue by martim00** [martim00/python-webpack-loader#2]

**Comment by martim00** [comment]
We have to figure how to use javascript libraries inside python code in the way webpack understands.

We need a way to tell webpack that a javascript module is needed by our python file.

```python
class Foo:
   def call_api(self):
       # using js_get is the way to tell transcrypt to keep 'get' in the generated javascript
       axios.js_get("www.google.com")
```

Suggestions:

1. use es6 import syntax inside a special block in the python file. That way we could parse it and notify webpack that our python file depends on the required js module. https://github.com/webpack-contrib/css-loader does that with css.

**Comment by icarito** [comment]
Transcrypt has its own import mechanism (which is independent of JS modules).

If we can produce valid Javascript import / require statements then webpack takes care of it. 

In my example with vue-loader I had to use `require` instead of `import` in order to have valid working syntax because I couldn't get Javascripthon to produce import statements. It may also be possible to intersperse JS within Python code, if the compiler supports it.

**Comment by martim00** [comment]
Cool! Maybe we could have a pre-processor that removes all import/require statements before sending the code to compilers. Then we get all those imports/requires and send directly to webpack. I think css-loader do that. I'll experiment this approach.

**Comment by icarito** [comment]
I had never thought of that! Intriguing! :-D

**Comment by icarito** [comment]
Thinking about #11 I think it's not sane to work against transpilers.

That said, a clearly defined feature called "Javascript style imports", could be cool: omit import statements from pre-compiled source and then re-inject imports statements without transpilation.

That way we'd write normal JS style imports.

**Comment by icarito** [comment]
One could replace import statements with marker no-ops.
Then one would replace the marker no-op found in the transpiled output with the original import statement.
That could work.

**Comment by azazel75** [comment]
I can have the imported modules as an "output" from JavaScripthon, It's just a matter of collecting them while rendering the JS. How you guys are using JavaScripthon? with files or stdin/sdtout/stderr?

**Comment by azazel75** [comment]
btw, you can mix JS with Python  in JavaScripthon by using the JS('Your js here') marker function. I just forgot to add it to the doc.

**Comment by icarito** [comment]
Hi Alberto! Thanks for checking out our little project :-)  Thanks for
coding Javascripthon!

We are using stdin/stdout/stderr to communicate with it.

I think it's fine to transpile imports like you are doing. Except there
are times where it's not possible to express the JS semantics (say with
{} or $ or @ or ~ or who knows what else). An option to leave import
statements alone and output them as-is would be great.

Otherwise this idea should work too.

**Comment by azazel75** [comment]
@icarito what do you mean with:
> it's not possible to express the JS semantics (say with {} or $ or @ or ~ or who knows what else)

It's clear that the module name in JS resembles a path more than Python's module import: that said `@` is managed by JavaScripthon and having `~`  (if it means the standard user's home path expansion) seems brutal anyway, I doubt that any serious project would advise you use it. It's like hardcoding a path in a source file. It's much better to use relative imports, which are supported in JavaScripthon.  I don't know what you use `$` and `{}`for in this context... boh.

About the output, i was referring to what @martim00 has written about module dependencies. For example, JavaScripthon may output a json with more rich contents like: a base64 encoded result JS, a dict with the dependencies (imports) of that module, another value containing the stderr (if it's useful to have it there) and another value containing the sourcemap, for example. Let me know if that could be useful.

**Comment by icarito** [comment]
@azazel75 extended output does sound interesting - I'm still interested in an IDE and this would provide interesting tooling. Previously I wrote [Jappy Activity](https://github.com/somosazucar/Jappy) with RapydScript-NG.

**Comment by icarito** [comment]
@azazel75 regarding the imports, the trouble is that Javascript uses a string where Python an identifier. A string is much more flexible, as e.g. Webpack can be wired to route imports in fancy ways. You are handling @ specially but what about other symbols, it's a slippery slope.

I am contributing a Nuxt framework module, but to produce Nuxt-compatible syntax I need to make imports like these: 
```python
JS("import VueCodeMirror from 'vue-codemirror-lite'")
JS("import Terminal from '~/components/xterm'")
#from vue__codemirror__lite import default as VueCodeMirror   # <- works
#from __.components.xterm import Terminal                     # <- doesn't work
```

This is the meaning of ~ (same as @, but didn't know it). It is *not* the home dir. :wink: 

ALIAS | DIRECTORY
-- | --
~ or @ | srcDir
~~ or @@ | rootDir

source: https://nuxtjs.org/guide/directory-structure#aliases

**Comment by martim00** [comment]
@azazel75 Thanks for your tips and for your work on JavaScripthon. It's a very cool project! 
I don't know if the extended output can help us in this case, because we are now supporting many transpilers. Maybe if we were a JavaScriphton specific loader we could use that. I'm afraid we are going to need a more generic approach here.

**Comment by martim00** [comment]
@icarito I'm doing an experiment with the pre-processing idea. Let me now what do you think about the approach and the syntax (https://github.com/martim00/python-webpack-loader/tree/feature/jsimports):

Example:
```
# js
from vue__codemirror__lite import default as VueCodeMirror
from __.components.xterm import Terminal 
# endjs

class PythonClass:
    def __init__():
         pass
```

The idea is to extract everything is inside # js and # endjs directives (js code), pass the python part to compilers and concatenate the js part back to the result before sending to webpack.

Do you think it's gonna work for your case?

**Comment by azazel75** [comment]
@martim00 Your approach seems a bit brutal ;-)  for the following reasons:

- mixing JS and Python in the same file makes linters go crazy;
- JavaScripthon may need to know which symbols are imported in order to do his calculation of what's to be put in  a `var` statement.
- the compiler may add `calculated` imports to execute runtime support functions without polluting the local module (for example to resolve deep equalness and so on). Now JavaScripthon writes those support functions inside the module, but i want to keep the door open to move these functions into a runtime package and import from there.

I suggest you look for some kind of real parsing, Webpack doesn't take care by itself of dependency management? Anyway it has to calculate dependency to reorder modules in the output bundle, maybe It has some kind of support for parsing JS already done and simple to use.

**Comment by azazel75** [comment]
@martim00 ah sorry. I was wrong, You don't mix JS and Python in  your example!?

**Comment by azazel75** [comment]
Anyway, I'm going to enhance JavaScripthon to produce that json aggregated output I was wring of in my previous comments. It seems to me that the most sane approach is to have a rich interface with the compiler and obtain those informations from it

**Comment by martim00** [comment]
@azazel75 @icarito Sorry, the example is wrong. The correct version is this:

```
# js
import VueCodeMirror from 'vue-codemirror-lite'
import Terminal from '~/components/xterm'
# endjs

class PythonClass:
    def __init__():
         pass
```
So yes, I'm mixing javascript with python. =)

**Comment by martim00** [comment]
@azazel75 But I understand your point. Maybe I'm in the wrong path in mixing both languages in the same file. I will take it to the desk again.

**Comment by azazel75** [comment]
@martim00 Why don't you just parse the JavaScript after it has been generated by the compiler?  Your source in javascripthon compatible source (as of current soon-to-be-released master branch):
```python
from vue__codemirror__lite import __default__ as VueCodeMirror
from tilde_.components.xterm import __default__ as Terminal

class PythonClass:
    def __init__():
         pass
```
I understand that you want your code to be adaptable to any backend regardless of the backend's features, but my advice is to let the backend to be in control of imports/exports  and then parse the JavaScript looking for imports, maybe  using  a facility that WebPack has for your code to use. Have you looked that up? Or as I said before, have the backend  not only giving back the translated code, but a richer set of info. Probably if you open up a issue in Transcrypt and Jiphy ansking for a richer output they will be eager to help you.

**Comment by azazel75** [comment]
I'm gonna add the JSON output anyway

**Comment by martim00** [comment]
@azazel75 @icarito 

Ok, so I finally had the time to investigate the issue. 

The problem lies in the fact that transcrypt has its own module system. So when I was trying to use axios library in my transcrypt code, an obvious python "import axios" was not working because of that. But at the same time I needed a way to signal webpack that axios was being used by my code, so it could handle dependency management of it. This was the initial motivation behind this issue.

In Javascripthon, the problem doesn't happen because the python import statement is converted seamless to es6 import. That way, webpack can handle dependency management as it does for every js code. So no modification in the loader is needed.

Having said that, I think one can use transcrypt pragma mechanism for workaround the problem:

```
__pragma__('js', '{}', '''
    var axios = require('axios')
        ''')

def on_response(response):
    print(response)

def main():
   axios.js_get('/api').then(on_response)

```

Sorry for the noise. I will commit examples for each backend in the next days.
